# Generated by Django 5.1.5 on 2025-01-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='user_default', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
